export const breedOptions = [
  { value: "Affenpinscher", label: "Affenpinscher" },
  { value: "Afghan Hound", label: "Afghan Hound" },
  { value: "Airedale Terrier", label: "Airedale Terrier" },
  { value: "Akita", label: "Akita" },
  { value: "Alaskan Malamute", label: "Alaskan Malamute" },
  { value: "American Cocker Spaniel", label: "American Cocker Spaniel" },
  { value: "Anatolian Shepherd Dog", label: "Anatolian Shepherd Dog" },
  { value: "Australian Cattle Dog", label: "Australian Cattle Dog" },
  { value: "Australian Shepherd", label: "Australian Shepherd" },
  { value: "Australian Silky Terrier", label: "Australian Silky Terrier" },
  { value: "Australian Terrier", label: "Australian Terrier" },
  { value: "Basenji", label: "Basenji" },
  { value: "Basset Fauve de Bretagne", label: "Basset Fauve de Bretagne" },
  { value: "Basset Hound", label: "Basset Hound" },
  { value: "Beagle", label: "Beagle" },
  { value: "Bearded Collie", label: "Bearded Collie" },
  { value: "Beauceron", label: "Beauceron" },
  { value: "Bedlington Terrier", label: "Bedlington Terrier" },
  { value: "Belgian Shepherd Dog (Groenendael", label: "Belgian Shepherd Dog (Groenendael)" },
  { value: "Belgian Shepherd Dog (Laekenois)", label: "Belgian Shepherd Dog (Laekenois)" },
  { value: "Belgian Shepherd Dog (Malinois)", label: "Belgian Shepherd Dog (Malinois)" },
  { value: "Belgian Shepherd Dog (Tervueren)", label: "Belgian Shepherd Dog (Tervueren)" },
  { value: "Bergamasco", label: "Bergamasco" },
  { value: "Bernese Mountain Dog", label: "Bernese Mountain Dog" },
  { value: "Bichon Frisé", label: "Bichon Frisé" },
  { value: "Bloodhound", label: "Bloodhound" },
  { value: "Border Collie", label: "Border Collie" },
  { value: "Border Terrier", label: "Border Terrier" },
  { value: "Borzoi", label: "Borzoi" },
  { value: "Boston Terrier", label: "Boston Terrier" },
  { value: "Bouvier des Flandres", label: "Bouvier des Flandres" },
  { value: "Boxer", label: "Boxer" },
  { value: "Bracco Italiano", label: "Bracco Italiano" },
  { value: "Briard", label: "Briard" },
  { value: "Brittany", label: "Brittany" },
  { value: "Bull Terrier", label: "Bull Terrier" },
  { value: "Bull Terrier (Miniature)", label: "Bull Terrier (Miniature)" },
  { value: "Bulldog", label: "Bulldog" },
  { value: "Bullmastiff", label: "Bullmastiff" },
  { value: "Cairn Terrier", label: "Cairn Terrier" },
  { value: "Canaan Dog", label: "Canaan Dog" },
  { value: "avalier King Charles Spaniel", label: "Cavalier King Charles Spaniel" },
  { value: "Cesky Terrier", label: "Cesky Terrier" },
  { value: "Chihuahua (Long Coat)", label: "Chihuahua (Long Coat)" },
  { value: "Chihuahua (Smooth Coat)", label: "Chihuahua (Smooth Coat)" },
  { value: "Chinese Crested", label: "Chinese Crested" },
  { value: "Chow Chow", label: "Chow Chow" },
  { value: "Clumber Spaniel", label: "Clumber Spaniel" },
  { value: "Cocker Spaniel", label: "Cocker Spaniel" },
  { value: "Collie (Rough)", label: "Collie (Rough)" },
  { value: "Collie (Smooth)", label: "Collie (Smooth)" },
  { value: "Curly Coated Retriever", label: "Curly Coated Retriever" },
  { value: "Dachshund (Long Haired)", label: "Dachshund (Long Haired)" },
  { value: "Dachshund (Miniature Long Haired)", label: "Dachshund (Miniature Long Haired)" },
  { value: "Dachshund (Miniature Smooth Haired)", label: "Dachshund (Miniature Smooth Haired)" },
  { value: "Dachshund (Miniature Wire Haired)", label: "Dachshund (Miniature Wire Haired)" },
  { value: "Dachshund (Smooth Haired)", label: "Dachshund (Smooth Haired)" },
  { value: "achshund (Wire Haired)", label: "Dachshund (Wire Haired)" },
  { value: "Dalmatian", label: "Dalmatian" },
  { value: "Dandie Dinmont Terrier", label: "Dandie Dinmont Terrier" },
  { value: "Deerhound", label: "Deerhound" },
  { value: "Dobermann", label: "Dobermann" },
  { value: "Dogue de Bordeaux", label: "Dogue de Bordeaux" },
  { value: "English Setter", label: "English Setter" },
  { value: "English Springer Spaniel", label: "English Springer Spaniel" },
  { value: "English Toy Terrier (Black & Tan)", label: "English Toy Terrier (Black & Tan)" },
  { value: "Eurasier", label: "Eurasier" },
  { value: "Field Spaniel", label: "Field Spaniel" },
  { value: "Finnish Lapphund", label: "Finnish Lapphund" },
  { value: "Finnish Spitz", label: "Finnish Spitz" },
  { value: "Flat Coated Retriever", label: "Flat Coated Retriever" },
  { value: "Fox Terrier (Smooth)", label: "Fox Terrier (Smooth)" },
  { value: "Fox Terrier (Wire)", label: "Fox Terrier (Wire)" },
  { value: "Foxhound", label: "Foxhound" },
  { value: "French Bulldog", label: "French Bulldog" },
  { value: "German Longhaired Pointer", label: "German Longhaired Pointer" },
  { value: "German Shepherd Dog", label: "German Shepherd Dog" },
  { value: "German Shorthaired Pointer", label: "German Shorthaired Pointer" },
  { value: "German Spitz (Klein)", label: "German Spitz (Klein)" },
  { value: "German Spitz (Mittel)", label: "German Spitz (Mittel)" },
  { value: "German Wirehaired Pointer", label: "German Wirehaired Pointer" },
  { value: "iant Schnauzer", label: "Giant Schnauzer" },
  { value: "Glen of Imaal Terrier", label: "Glen of Imaal Terrier" },
  { value: "Golden Retriever", label: "Golden Retriever" },
  { value: "Gordon Setter", label: "Gordon Setter" },
  { value: "Grand Bleu de Gascogne", label: "Grand Bleu de Gascogne" },
  { value: "Great Dane", label: "Great Dane" },
  { value: "Greenland Dog", label: "Greenland Dog" },
  { value: "Greyhound", label: "Greyhound" },
  { value: "Griffon Bruxellois", label: "Griffon Bruxellois" },
  { value: "Hamiltonstövare", label: "Hamiltonstövare" },
  { value: "Havanese", label: "Havanese" },
  { value: "Hungarian Kuvasz", label: "Hungarian Kuvasz" },
  { value: "Hungarian Puli", label: "Hungarian Puli" },
  { value: "Hungarian Vizsla", label: "Hungarian Vizsla" },
  { value: "Hungarian Wirehaired Vizsla", label: "Hungarian Wirehaired Vizsla" },
  { value: "Ibizan Hound", label: "Ibizan Hound" },
  { value: "Icelandic Sheepdog", label: "Icelandic Sheepdog" },
  { value: "Irish Red and White Setter", label: "Irish Red and White Setter" },
  { value: "Irish Setter", label: "Irish Setter" },
  { value: "Irish Terrier", label: "Irish Terrier" },
  { value: "Irish Water Spaniel", label: "Irish Water Spaniel" },
  { value: "Irish Wolfhound", label: "Irish Wolfhound" },
  { value: "Italian Greyhound", label: "Italian Greyhound" },
  { value: "Italian Spinone", label: "Italian Spinone" },
  { value: "Jack Russell Terrier", label: "Jack Russell Terrier" },
  { value: "Japanese Akita Inu", label: "Japanese Akita Inu" },
  { value: "Japanese Chin", label: "Japanese Chin" },
  { value: "Japanese Shiba Inu", label: "Japanese Shiba Inu" },
  { value: "Japanese Spitz", label: "Japanese Spitz" },
  { value: "Keeshond", label: "Keeshond" },
  { value: "Kerry Blue Terrier", label: "Kerry Blue Terrier" },
  { value: "King Charles Spaniel", label: "King Charles Spaniel" },
  { value: "Komondor", label: "Komondor" },
  { value: "Kooikerhondje", label: "Kooikerhondje" },
  { value: "Korean Jindo", label: "Korean Jindo" },
  { value: "Labrador Retriever", label: "Labrador Retriever" },
  { value: "Lagotto Romagnolo", label: "Lagotto Romagnolo" },
  { value: "Lakeland Terrier", label: "Lakeland Terrier" },
  { value: "Lancashire Heeler", label: "Lancashire Heeler" },
  { value: "Large Munsterlander", label: "Large Munsterlander" },
  { value: "Leonberger", label: "Leonberger" },
  { value: "Lhasa Apso", label: "Lhasa Apso" },
  { value: "Lowchen (Little Lion Dog)", label: "Lowchen (Little Lion Dog)" },
  { value: "Maltese", label: "Maltese" },
  { value: "Manchester Terrier", label: "Manchester Terrier" },
  { value: "Maremma Sheepdog", label: "Maremma Sheepdog" },
  { value: "Mastiff", label: "Mastiff" },
  { value: "Miniature Pinscher", label: "Miniature Pinscher" },
  { value: "Miniature Schnauzer", label: "Miniature Schnauzer" },
  { value: "Neapolitan Mastiff", label: "Neapolitan Mastiff" },
  { value: "Newfoundland", label: "Newfoundland" },
  { value: "Norfolk Terrier", label: "Norfolk Terrier" },
  { value: "Norwegian Buhund", label: "Norwegian Buhund" },
  { value: "Norwegian Elkhound", label: "Norwegian Elkhound" },
  { value: "Norwegian Lundehund", label: "Norwegian Lundehund" },
  { value: "Norwich Terrier", label: "Norwich Terrier" },
  { value: "Nova Scotia Duck Tolling Retriever", label: "Nova Scotia Duck Tolling Retriever" },
  { value: "Old English Sheepdog", label: "Old English Sheepdog" },
  { value: "Otterhound", label: "Otterhound" },
  { value: "Papillon", label: "Papillon" },
  { value: "Parson Russell Terrier", label: "Parson Russell Terrier" },
  { value: "Pekingese", label: "Pekingese" },
  { value: "Pembroke Welsh Corgi", label: "Pembroke Welsh Corgi" },
  { value: "Petit Basset Griffon Vendéen", label: "Petit Basset Griffon Vendéen" },
  { value: "Pharaoh Hound", label: "Pharaoh Hound" },
  { value: "Pointer", label: "Pointer" },
  { value: "Polish Lowland Sheepdog", label: "Polish Lowland Sheepdog" },
  { value: "Pomeranian", label: "Pomeranian" },
  { value: "Poodle (Miniature)", label: "Poodle (Miniature)" },
  { value: "Poodle (Standard)", label: "Poodle (Standard)" },
  { value: "Toy Poodle", label: "Toy Poodle" },
  { value: "Portuguese Podengo", label: "Portuguese Podengo" },
  { value: "Portuguese Water Dog", label: "Portuguese Water Dog" },
  { value: "Pug", label: "Pug" },
  { value: "Pyrenean Mountain Dog", label: "Pyrenean Mountain Dog" },
  { value: "Pyrenean Sheepdog (Long Haired)", label: "Pyrenean Sheepdog (Long Haired)" },
  { value: "Rhodesian Ridgeback", label: "Rhodesian Ridgeback" },
  { value: "Rottweiler", label: "Rottweiler" },
  { value: "Russian Black Terrier", label: "Russian Black Terrier" },
  { value: "Saluki", label: "Saluki" },
  { value: "Samoyed", label: "Samoyed" },
  { value: "Schipperke", label: "Schipperke" },
  { value: "Schnauzer", label: "Schnauzer" },
  { value: "Scottish Terrier", label: "Scottish Terrier" },
  { value: "Sealyham Terrier", label: "Sealyham Terrier" },
  { value: "Shetland Sheepdog", label: "Shetland Sheepdog" },
  { value: "Shih Tzu", label: "Shih Tzu" },
  { value: "Siberian Husky", label: "Siberian Husky" },
  { value: "Skye Terrier", label: "Skye Terrier" },
  { value: "Sloughi", label: "Sloughi" },
  { value: "Soft Coated Wheaten Terrier", label: "Soft Coated Wheaten Terrier" },
  { value: "Spaniel (American Cocker)", label: "Spaniel (American Cocker)" },
  { value: "Spaniel (Clumber)", label: "Spaniel (Clumber)" },
  { value: "Spaniel (Field)", label: "Spaniel (Field)" },
  { value: "Spaniel (Irish Water)", label: "Spaniel (Irish Water)" },
  { value: "Spaniel (Sussex)", label: "Spaniel (Sussex)" },
  { value: "Spaniel (Welsh Springer)", label: "Spaniel (Welsh Springer)" },
  { value: "Spanish Water Dog", label: "Spanish Water Dog" },
  { value: "St. Bernard", label: "St. Bernard" },
  { value: "Staffordshire Bull Terrier", label: "Staffordshire Bull Terrier" },
  { value: "Standard Schnauzer", label: "Standard Schnauzer" },
  { value: "Swedish Lapphund", label: "Swedish Lapphund" },
  { value: "Swedish Vallhund", label: "Swedish Vallhund" },
  { value: "Tibetan Mastiff", label: "Tibetan Mastiff" },
  { value: "Tibetan Spaniel", label: "Tibetan Spaniel" },
  { value: "Tibetan Terrier", label: "Tibetan Terrier" },
  { value: "Toy Manchester Terrier", label: "Toy Manchester Terrier" },
  { value: "Vizsla (Hungarian)", label: "Vizsla (Hungarian)" },
  { value: "Weimaraner", label: "Weimaraner" },
  { value: "Welsh Corgi (Cardigan)", label: "Welsh Corgi (Cardigan)" },
  { value: "Welsh Corgi (Pembroke)", label: "Welsh Corgi (Pembroke)" },
  { value: "Welsh Terrier", label: "Welsh Terrier" },
  { value: "West Highland White Terrier", label: "West Highland White Terrier" },
  { value: "Whippet", label: "Whippet" },
  { value: "White Swiss Shepherd Dog", label: "White Swiss Shepherd Dog" },
  { value: "Yorkshire Terrier", label: "Yorkshire Terrier" },
];